openapi: 3.0.0
info:
  version: 1.0.0
  title: RBKmoney Sender API
  description:
    $ref: './docs/api.md'
  termsOfService: http://rbk.money/
  contact:
    name: RBKmoney support team
    email: support@rbk.money
    url: 'https://developer.rbk.money'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /message/feedback:
    $ref: ./paths/message-feedback.yaml
  '/message/exclusion-rules/{ruleID}':
    $ref: './paths/message-exclusion-rules@{ruleID}.yaml'
  '/message/exclusion-rules/{ruleID}/delete':
    $ref: './paths/message-exclusion-rules@{ruleID}@delete.yaml'
  '/message/exclusion-rules/search':
    $ref: './paths/message-exclusion-rules@search.yaml'
  '/message/exclusion-rules/create':
    $ref: './paths/message-exclusion-rules@create.yaml'
servers:
  - url: 'https://{subdomain}.rbk.money/sender/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v1
        default: v1
security:
  - bearer: []
components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
